name: CSV Lint
on: push

jobs:
  youtube-lint:
    runs-on: ubuntu-latest
    name: Youtube CSV lint
    steps:
    - uses: actions/checkout@v1
    - name: "Read file contents"
      id: read-csv
      uses: andstor/file-reader-action@v1
      with:
        path: youtube-channels.csv
    - name: Find duplicate IDs
      id: check-csv
      uses: stephanebruckert/csv-contribution-action@1.0.0
      with:
        file-content: "${{ steps.read-csv.outputs.contents }}"
        find-duplicates: "true"

  discogs-lint:
    runs-on: ubuntu-latest
    name: Discogs CSV lint
    steps:
      - uses: actions/checkout@v1
      - name: "Read file contents"
        id: read-csv
        uses: andstor/file-reader-action@v1
        with:
          path: discogs-labels.csv
      - name: Find duplicate IDs
        id: check-csv
        uses: stephanebruckert/csv-contribution-action@1.0.0
        with:
          file-content: "${{ steps.read-csv.outputs.contents }}"
          find-duplicates: "true"
