name: CSV Lint
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: csv lint
    steps:
    - uses: actions/checkout@v1
    - name: Read package.json
      id: package
      uses: juliangruber/read-file-action@v1
      with:
        path: youtube-channels.csv
    - name: Check CSV
      id: check-csv
      uses: stephanebruckert/csv-contribution-action@main
      with:
        file-content: ${{ steps.template.outputs.content }}
    - name: Get the output time
      run: echo "The time was ${{ steps.check-csv.outputs.time }}"